/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState } from 'react';
import { Trophy, Sparkles, BookmarkCheck, BookmarkPlus, Share2, Check } from 'lucide-react';
import { BALL_PALETTE } from './LotteryMachine';

interface DrawnResultsProps {
  drawnNumbers: number[];
  target: number;
  min?: number;
  max?: number;
  machineType?: 'mechanical' | 'blower';
  poolName?: string;
  onSaveDraw?: () => void;
  isSaved?: boolean;
}

export const DrawnResults: React.FC<DrawnResultsProps> = ({
  drawnNumbers,
  target,
  min = 1,
  max = 49,
  machineType = 'mechanical',
  poolName,
  onSaveDraw,
  isSaved = false,
}) => {
  const [copied, setCopied] = useState(false);
  const isComplete = drawnNumbers.length >= target && target > 0;

  const generateShareSummary = () => {
    if (drawnNumbers.length === 0) return '';
    const now = new Date();
    const sorted = [...drawnNumbers].sort((a, b) => a - b);
    const sum = drawnNumbers.reduce((a, b) => a + b, 0);
    const avg = (sum / drawnNumbers.length).toFixed(1);
    const oddCount = drawnNumbers.filter((n) => n % 2 !== 0).length;
    const evenCount = drawnNumbers.filter((n) => n % 2 === 0).length;

    const poolDesc = poolName ? `${poolName} (${min} to ${max})` : `${min} to ${max}`;

    return [
      `🎱 LOTTERY DRAW RESULTS${isComplete ? ' (FULL DRAW)' : ''}`,
      `━━━━━━━━━━━━━━━━━━━━━━━━━━━`,
      `📅 Date: ${now.toLocaleDateString(undefined, {
        month: 'short',
        day: 'numeric',
        year: 'numeric',
      })} at ${now.toLocaleTimeString(undefined, {
        hour: '2-digit',
        minute: '2-digit',
      })}`,
      `🎯 Pool: ${poolDesc} (${drawnNumbers.length}/${target} picked)`,
      `⚙️ Mechanism: ${machineType === 'mechanical' ? 'Mechanical Paddles' : 'Cyclone Air Blower'}`,
      `━━━━━━━━━━━━━━━━━━━━━━━━━━━`,
      `🏆 Drawn Order: [ ${drawnNumbers.join(' - ')} ]`,
      `✨ Sorted:      [ ${sorted.join(', ')} ]`,
      `━━━━━━━━━━━━━━━━━━━━━━━━━━━`,
      `📊 Statistics: Sum = ${sum} | Average = ${avg} | Odd: ${oddCount} / Even: ${evenCount}`,
      `━━━━━━━━━━━━━━━━━━━━━━━━━━━`,
      `Generated by Lottery Machine Simulator`,
    ]
      .filter(Boolean)
      .join('\n');
  };

  const handleShare = async () => {
    if (drawnNumbers.length === 0) return;
    const summary = generateShareSummary();

    // Prefer native share if available (e.g. mobile/supported browsers)
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'Lottery Draw Results',
          text: summary,
        });
        setCopied(true);
        setTimeout(() => setCopied(false), 2200);
        return;
      } catch {
        // User dismissed sheet or failed, proceed to clipboard
      }
    }

    try {
      await navigator.clipboard.writeText(summary);
      setCopied(true);
      setTimeout(() => setCopied(false), 2200);
    } catch {
      // Fallback
      const textarea = document.createElement('textarea');
      textarea.value = summary;
      textarea.style.position = 'fixed';
      textarea.style.opacity = '0';
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2200);
    }
  };

  return (
    <div className="w-full max-w-md bg-white border border-slate-200/80 rounded-2xl shadow-sm p-4 flex flex-col gap-3">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div className="p-1.5 bg-amber-500/10 text-amber-600 rounded-lg">
            <Trophy className="w-4 h-4" />
          </div>
          <span className="text-xs font-bold uppercase tracking-wider text-slate-700">
            Drawn Winning Numbers
          </span>
        </div>
        <div className="flex items-center gap-2">
          {onSaveDraw && drawnNumbers.length > 0 && (
            <button
              onClick={onSaveDraw}
              disabled={isSaved}
              className={`flex items-center gap-1 text-[11px] font-bold px-2.5 py-0.5 rounded-full border transition-all cursor-pointer ${
                isSaved
                  ? 'bg-emerald-50 text-emerald-700 border-emerald-200'
                  : 'bg-indigo-50 hover:bg-indigo-100 text-indigo-700 border-indigo-200'
              }`}
              title={isSaved ? 'Saved to history log below' : 'Save current draw to history'}
            >
              {isSaved ? (
                <>
                  <BookmarkCheck className="w-3 h-3 text-emerald-600" />
                  Saved
                </>
              ) : (
                <>
                  <BookmarkPlus className="w-3 h-3 text-indigo-600" />
                  Save Draw
                </>
              )}
            </button>
          )}
          <span className="text-xs font-semibold px-2 py-0.5 rounded-full bg-slate-100 text-slate-600">
            {drawnNumbers.length} / {target} Picked
          </span>
        </div>
      </div>

      {/* Number Balls Display */}
      <div className="flex flex-wrap items-center gap-2.5 min-h-[52px] p-2.5 bg-slate-50/80 rounded-xl border border-slate-200/60 justify-center">
        {drawnNumbers.length === 0 ? (
          <span className="text-xs text-slate-400 italic">
            Waiting for draw... Click &ldquo;Draw 1 Ball&rdquo; or &ldquo;Auto Draw All&rdquo;
          </span>
        ) : (
          drawnNumbers.map((num, idx) => {
            const pIndex = (num - 1) % BALL_PALETTE.length;
            const theme = BALL_PALETTE[pIndex >= 0 ? pIndex : 0];
            const isLatest = idx === drawnNumbers.length - 1;

            return (
              <div
                key={`drawn-${num}`}
                className="relative flex items-center justify-center w-10 h-10 rounded-full shadow-sm select-none"
                style={{
                  background: theme.bg,
                }}
                title={`Ball #${num}`}
              >
                {/* Animated "New" Pill Badge for the newest settled ball */}
                {isLatest && (
                  <div className="absolute -top-2.5 -right-1.5 px-1 py-0.2 rounded-full bg-amber-500 text-white font-black text-[8px] uppercase tracking-wider flex items-center gap-0.5 pointer-events-none z-20">
                    <Sparkles className="w-2 h-2 text-white" />
                    <span>New</span>
                  </div>
                )}

                {/* White inner decal circle */}
                <div className="w-6 h-6 rounded-full bg-white flex items-center justify-center">
                  <span className="font-extrabold text-xs text-slate-900 leading-none">
                    {num}
                  </span>
                </div>
              </div>
            );
          })
        )}
      </div>

      {/* Actions & Completion Bar */}
      <div className="flex flex-col gap-2">
        {isComplete && (
          <div className="flex items-center justify-center gap-1.5 py-1.5 px-3 rounded-lg bg-emerald-50 border border-emerald-200 text-emerald-700 text-xs font-bold animate-in fade-in">
            <Sparkles className="w-3.5 h-3.5 text-emerald-500" />
            Full Draw Complete! Congratulations!
          </div>
        )}

        {drawnNumbers.length > 0 && (
          <div className="flex items-center justify-between pt-1 border-t border-slate-100">
            <span className="text-[11px] text-slate-400">
              {isComplete ? 'All numbers extracted' : `${target - drawnNumbers.length} more ball${target - drawnNumbers.length === 1 ? '' : 's'} to pick`}
            </span>
            <button
              onClick={handleShare}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-bold transition-all cursor-pointer ${
                copied
                  ? 'bg-emerald-600 text-white'
                  : 'bg-slate-900 hover:bg-slate-800 active:scale-95 text-white'
              }`}
              title="Copy formatted draw summary to clipboard or share"
            >
              {copied ? (
                <>
                  <Check className="w-3.5 h-3.5 text-white" />
                  <span>Copied Summary!</span>
                </>
              ) : (
                <>
                  <Share2 className="w-3.5 h-3.5 text-slate-300" />
                  <span>Share Result</span>
                </>
              )}
            </button>
          </div>
        )}
      </div>
    </div>
  );
};
