/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

interface ShareSummaryInput {
    numbers: number[];
    target: number;
    min: number;
    max: number;
    poolName?: string;
    machineType: 'mechanical' | 'blower';
}

export const generateShareSummary = ({
    numbers, target, min, max, poolName, machineType,
}: ShareSummaryInput): string => {
    if (numbers.length === 0) return '';
    const now = new Date();
    const sorted = [...numbers].sort((a, b) => a - b);
    const sum = numbers.reduce((a, b) => a + b, 0);
    const avg = (sum / numbers.length).toFixed(1);
    const oddCount = numbers.filter((n) => n % 2 !== 0).length;
    const evenCount = numbers.length - oddCount;
    const poolDesc = poolName ? `${poolName} (${min} to ${max})` : `${min} to ${max}`;

    return [
        `🎱 LOTTERY DRAW RESULTS`,
        `━━━━━━━━━━━━━━━━━━━━━━━━━━━`,
        `📅 Date: ${now.toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' })} at ${now.toLocaleTimeString(undefined, { hour: '2-digit', minute: '2-digit' })}`,
        `🎯 Pool: ${poolDesc} (${numbers.length}/${target} picked)`,
        `⚙️ Mechanism: ${machineType === 'mechanical' ? 'Mechanical Paddles' : 'Cyclone Air Blower'}`,
        `━━━━━━━━━━━━━━━━━━━━━━━━━━━`,
        `🏆 Drawn Order: [ ${numbers.join(' - ')} ]`,
        `✨ Sorted:      [ ${sorted.join(', ')} ]`,
        `━━━━━━━━━━━━━━━━━━━━━━━━━━━`,
        `📊 Statistics: Sum = ${sum} | Average = ${avg} | Odd: ${oddCount} / Even: ${evenCount}`,
        `━━━━━━━━━━━━━━━━━━━━━━━━━━━`,
        `Generated by Lottery Machine Simulator`,
    ].join('\n');
};

export const shareOrCopy = async (text: string, title = 'Lottery Draw Results'): Promise<boolean> => {
    if (text.length === 0) return false;

    if (navigator.share) {
        try {
            await navigator.share({ title, text });
            return true;
        } catch {
            // User dismissed the share sheet — fall through to clipboard
        }
    }

    try {
        await navigator.clipboard.writeText(text);
        return true;
    } catch {
        try {
            const textarea = document.createElement('textarea');
            textarea.value = text;
            textarea.style.position = 'fixed';
            textarea.style.opacity = '0';
            document.body.appendChild(textarea);
            textarea.select();
            document.execCommand('copy');
            document.body.removeChild(textarea);
            return true;
        } catch {
            return false;
        }
    }
};